# Commodities

In [44]:
import requests
import pandas as pd
import os

# USDA API Key
USDA_API_KEY = os.getenv("USDA_API_KEY")

# Base URL
BASE_URL = "https://api.fas.usda.gov"

# Parameters for request
params = {"api_key": USDA_API_KEY}
ENDPOINT = f"/api/psd/commodities"

response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    commodities = pd.concat(
        [
            df[df["commodityName"].str.contains("corn", case=False)],
            df[df["commodityName"].str.contains("soybean", case=False)],
            df[df["commodityName"].str.contains("wheat", case=False)]
        ],
        ignore_index=True,
    )
else:
    print(f"Error: {response.status_code}, {response.text}")

commodities

  commodityCode             commodityName
0       0440000                      Corn
1       0813100             Meal, Soybean
2       0813101     Meal, Soybean (Local)
3       4232000              Oil, Soybean
4       4232001      Oil, Soybean (Local)
5       2222000          Oilseed, Soybean
6       2222001  Oilseed, Soybean (Local)
7       0410000                     Wheat

# Countries

In [45]:
ENDPOINT = f"/api/psd/countries"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    countries = pd.concat(
        [
            df[df["countryName"].str.contains("united states", case=False)],
            df[df["countryName"].str.contains("mexico", case=False)],
            df[df["countryName"].str.contains("japan", case=False)],
            df[df["countryName"].str.contains("korea, south", case=False)],
            df[df["countryName"].str.contains("colombia", case=False)],
            df[df["countryName"].str.contains("european union", case=False)],
            df[df["countryName"].str.contains("taiwan", case=False)],
            df[df["countryName"].str.contains("guatemala", case=False)],
            df[df["countryName"].str.contains("vietnam", case=False) & ~df["countryName"].str.contains("Republic", case=False)],
            df[df["countryName"].str.contains("canada", case=False)],
            df[df["countryName"].str.contains("honduras", case=False)],
            df[df["countryName"].str.contains("philippines", case=False)],
            df[df["countryName"].str.contains("nigeria", case=False)],
            df[df["countryName"].str.contains("indonesia", case=False)],
            df[df["countryName"].str.contains("thailand", case=False)],
            df[df["countryName"].str.contains("china", case=False)],
            df[df["countryName"].str.contains("egypt", case=False)],
            df[df["countryName"].str.contains("pakistan", case=False)],
            df[df["countryName"].str.contains("bangladesh", case=False)]
        ],
        ignore_index=True,
    )
else:
    print(f"Error: {response.status_code}, {response.text}")

countries

   countryCode     countryName regionCode gencCode
0           US   United States        R01      USA
1           MX          Mexico        R01      MEX
2           JA           Japan        R18      JPN
3           KS    Korea, South        R18      KOR
4           CO        Colombia        R04      COL
5           E4  European Union        R05     None
6           TW          Taiwan        R18      TWN
7           GT       Guatemala        R03      GTM
8           VM         Vietnam        R17      VNM
9           CA          Canada        R01      CAN
10          HO        Honduras        R03      HND
11          RP     Philippines        R17      PHL
12          NI         Nigeria        R11      NGA
13          ID       Indonesia        R17      IDN
14          TH        Thailand        R17      THA
15          CH           China        R18      CHN
16          EG           Egypt        R10      EGY
17          PK        Pakistan        R12      PAK
18          BG      Bangladesh        R12      BGD

# Units

In [46]:
unit_ids = [4, 8, 23, 26] # From selected commodities

ENDPOINT = f"/api/psd/unitsOfMeasure"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    units = df[df["unitId"].isin(unit_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

units

    unitId       unitDescription
3        4  (1000 HA)
7        8  (1000 MT)
22      23  (PERCENT)
25      26  (MT/HA)

# All Attributes

In [47]:
all_attribute_ids = [4, 181, 81, 84, 86, 88, 113, 130, 192, 125, 176, 178, 184, 57, 28, 20, 140, 7, 149, 161, 194] # From selected commodities

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    attributes = df[df["attributeId"].isin(all_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

attributes

    attributeId          attributeName
1             4         Area Harvested
4             7                  Crush
5            20       Beginning Stocks
9            28             Production
23           57                Imports
32           81             TY Imports
34           84      TY Imp. from U.S.
35           86           Total Supply
36           88                Exports
43          113             TY Exports
49          125   Domestic Consumption
52          130  Feed Dom. Consumption
58          140  Industrial Dom. Cons.
62          149    Food Use Dom. Cons.
69          161  Feed Waste Dom. Cons.
76          176          Ending Stocks
77          178     Total Distribution
78          181   Extr. Rate, 999.9999
81          184                  Yield
82          192        FSI Consumption
83          194                    SME

# Corn Attributes

In [48]:
corn_attribute_ids = [4, 20, 28, 57, 81, 84, 86, 88, 113, 125, 130, 176, 178, 184, 192]

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    corn_attributes = df[df["attributeId"].isin(corn_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

corn_attributes

    attributeId          attributeName
1             4         Area Harvested
5            20       Beginning Stocks
9            28             Production
23           57                Imports
32           81             TY Imports
34           84      TY Imp. from U.S.
35           86           Total Supply
36           88                Exports
43          113             TY Exports
49          125   Domestic Consumption
52          130  Feed Dom. Consumption
76          176          Ending Stocks
77          178     Total Distribution
81          184                  Yield
82          192        FSI Consumption

# Soybeans Attributes

In [49]:
soybeans_attribute_ids = [4, 7, 20, 28, 57, 86, 88, 125, 149, 161, 176, 178, 184]

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    soybeans_attributes = df[df["attributeId"].isin(soybeans_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

soybeans_attributes

    attributeId          attributeName
1             4         Area Harvested
4             7                  Crush
5            20       Beginning Stocks
9            28             Production
23           57                Imports
35           86           Total Supply
36           88                Exports
49          125   Domestic Consumption
62          149    Food Use Dom. Cons.
69          161  Feed Waste Dom. Cons.
76          176          Ending Stocks
77          178     Total Distribution
81          184                  Yield

# Soybean Meal Attributes

In [50]:
soybean_meal_attribute_ids = [7, 20, 28, 57, 86, 88, 125, 140, 149, 161, 176, 178, 181, 194]

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    soybean_meal_attributes = df[df["attributeId"].isin(soybean_meal_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

soybean_meal_attributes

    attributeId          attributeName
4             7                  Crush
5            20       Beginning Stocks
9            28             Production
23           57                Imports
35           86           Total Supply
36           88                Exports
49          125   Domestic Consumption
58          140  Industrial Dom. Cons.
62          149    Food Use Dom. Cons.
69          161  Feed Waste Dom. Cons.
76          176          Ending Stocks
77          178     Total Distribution
78          181   Extr. Rate, 999.9999
83          194                    SME

# Soybean Oil Attributes

In [51]:
soybean_oil_attribute_ids = [7, 20, 28, 57, 86, 88, 125, 140, 149, 161, 176, 178, 181]

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    soybean_oil_attributes = df[df["attributeId"].isin(soybean_oil_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

soybean_oil_attributes

    attributeId          attributeName
4             7                  Crush
5            20       Beginning Stocks
9            28             Production
23           57                Imports
35           86           Total Supply
36           88                Exports
49          125   Domestic Consumption
58          140  Industrial Dom. Cons.
62          149    Food Use Dom. Cons.
69          161  Feed Waste Dom. Cons.
76          176          Ending Stocks
77          178     Total Distribution
78          181   Extr. Rate, 999.9999

# Wheat Attributes

In [52]:
wheat_attribute_ids = [4, 20, 28, 57, 81, 84, 86, 88, 113, 125, 130, 176, 178, 184, 192]

ENDPOINT = f"/api/psd/commodityAttributes"
response = requests.get(BASE_URL + ENDPOINT, params=params)

if response.status_code == 200:
    data = response.json()
    df = pd.DataFrame(data)
    wheat_attributes = df[df["attributeId"].isin(wheat_attribute_ids)]
else:
    print(f"Error: {response.status_code}, {response.text}")

wheat_attributes

    attributeId          attributeName
1             4         Area Harvested
5            20       Beginning Stocks
9            28             Production
23           57                Imports
32           81             TY Imports
34           84      TY Imp. from U.S.
35           86           Total Supply
36           88                Exports
43          113             TY Exports
49          125   Domestic Consumption
52          130  Feed Dom. Consumption
76          176          Ending Stocks
77          178     Total Distribution
81          184                  Yield
82          192        FSI Consumption